version: '4.1.2'

services:
  web:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
